"""Agentic Cuts — the agentic NLE.

Multi-tenant agentic video production system. Run from inside any AI
coding assistant, drives a real timeline, deterministic by default.

Public API lives in `agentic_cuts.lib`.
"""

from agentic_cuts.lib import (
    BaseTool,
    BrandCaptionDefaults,
    BrandColor,
    BrandIntroOutro,
    BrandKit,
    BrandKitLoadError,
    BrandLogo,
    BrandTypography,
    BrandVoice,
    BudgetConfig,
    BudgetExceededError,
    BudgetMode,
    Capability,
    CaptionColors,
    CaptionEmphasis,
    CaptionMotion,
    CaptionPosition,
    CaptionPreset,
    CaptionPresetLoadError,
    CaptionSafeZone,
    CaptionTypography,
    Checkpoint,
    CheckpointConfig,
    CheckpointPolicy,
    CostTracker,
    DeliveryPromise,
    DeliveryPromiseDefaults,
    MediaProfile,
    PROFILES,
    PipelineLoadError,
    PipelineManifest,
    ReviewConfig,
    RunCache,
    ScoreCard,
    Selector,
    SkillRAG,
    SlideshowRisk,
    StageManifest,
    StyleFamily,
    Tier,
    ToolRegistry,
    ToolResult,
    ValidationResult,
    cache_key,
    detect_slideshow_risk,
    discover_pipelines,
    discover_presets,
    keyframe_aligned_cut,
    load_brand_kit,
    load_manifest,
    load_preset,
    plan_cut,
    profile_for,
    registry,
    select_provider,
    validate_plan,
)

__version__ = "0.1.0"

__all__ = [
    "BaseTool", "ToolResult", "Capability", "Tier",
    "ToolRegistry", "registry",
    "ScoreCard", "Selector", "select_provider",
    "Checkpoint",
    "MediaProfile", "PROFILES", "profile_for",
    "CostTracker", "BudgetMode", "BudgetExceededError",
    "DeliveryPromise", "validate_plan", "ValidationResult",
    "SlideshowRisk", "detect_slideshow_risk",
    "RunCache", "cache_key",
    "SkillRAG",
    "keyframe_aligned_cut", "plan_cut",
    "__version__",
]
