import Link from "next/link";
import { notFound } from "next/navigation";
import { DEMO_PLANS } from "@/lib/render-plan";
import { StageRow } from "@/components/stage-row";
import { TimelineTrack } from "@/components/timeline-track";

export default async function TimelinePage({
  params,
}: {
  params: Promise<{ plan: string }>;
}) {
  const { plan: planName } = await params;
  const plan = DEMO_PLANS[planName];
  if (!plan) notFound();

  // Synthesize a fake-but-plausible timeline from the stages so the visitor
  // sees something on the track. Real renders fill this from the Python engine.
  const totalSec = 60;
  const segLen = totalSec / plan.stages.length;
  const fakeClips = plan.stages.map((s, i) => ({
    id: s.name,
    start_sec: i * segLen,
    end_sec: (i + 1) * segLen,
    label: s.name,
  }));

  return (
    <main className="max-w-6xl mx-auto px-6 py-12">
      <nav className="mb-10 text-sm">
        <Link href="/" className="text-white/55 hover:text-yellow-400">← back</Link>
      </nav>

      <header className="mb-10">
        <div className="font-mono text-xs text-yellow-400 uppercase tracking-wider mb-3">
          {plan.pipeline.type} pipeline
        </div>
        <h1 className="text-5xl font-black tracking-tight mb-4">
          {plan.pipeline.name}
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 text-sm">
          <Stat label="Aspect" value={plan.delivery_promise.target_aspect} />
          <Stat label="Profile" value={`${plan.render_target.name} · ${plan.render_target.resolution} @ ${plan.render_target.fps}`} />
          <Stat label="Cap" value={`$${plan.budget.cap_usd.toFixed(2)} ${plan.budget.mode}`} />
          <Stat label="Stages" value={String(plan.stages.length)} />
        </div>
      </header>

      <section className="mb-10">
        <TimelineTrack totalDurationSec={totalSec} clips={fakeClips} />
      </section>

      <section className="mb-10">
        <h2 className="font-black text-xl mb-4 tracking-tight">Stages</h2>
        <div className="grid gap-2">
          {plan.stages.map((s) => (
            <StageRow key={s.name} stage={s} status="pending" />
          ))}
        </div>
      </section>

      <section className="mb-10">
        <h2 className="font-black text-xl mb-4 tracking-tight">Delivery promise</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 text-sm">
          <Bool label="Motion" v={plan.delivery_promise.requires_motion} />
          <Bool label="Audio" v={plan.delivery_promise.requires_audio} />
          <Bool label="Captions" v={plan.delivery_promise.requires_captions} />
          <Bool label="Narration" v={plan.delivery_promise.requires_narration} />
          <Bool label="Music" v={plan.delivery_promise.requires_music} />
          <Stat label="Tolerance" value={`±${plan.delivery_promise.duration_tolerance_sec}s`} />
        </div>
      </section>

      <footer className="mt-24 pt-8 border-t border-white/10 text-xs text-white/40">
        Pipeline shape generated by `agentic-cuts plan --pipeline {plan.pipeline.name}`. The
        Python engine does the real work; this UI supervises it.
      </footer>
    </main>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="border border-white/10 rounded-md p-3 bg-white/[0.02]">
      <div className="text-[10px] uppercase tracking-wider text-white/40 mb-1">{label}</div>
      <div className="font-bold">{value}</div>
    </div>
  );
}

function Bool({ label, v }: { label: string; v: boolean }) {
  return (
    <div className="border border-white/10 rounded-md p-3 bg-white/[0.02] flex items-center justify-between">
      <span className="text-[10px] uppercase tracking-wider text-white/40">{label}</span>
      <span className={v ? "text-cyan-400 font-bold" : "text-white/30"}>{v ? "yes" : "no"}</span>
    </div>
  );
}
